---
abstract: 'make simple lightweight record-like structures'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  Test::Fatal: '0'
  Test::More: '0.88'
configure_requires:
  Module::Build: '0.4004'
dynamic_config: 1
generated_by: 'Module::Build version 0.4224, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Struct-Dumb
provides:
  Struct::Dumb:
    file: lib/Struct/Dumb.pm
    version: '0.12'
resources:
  license: http://dev.perl.org/licenses/
version: '0.12'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
